NB_CARDS_MAX_FOR_PILE = 6
NB_ROUNDS_BY_GAME = 5

DEBUG = True
SHOW_DETAILS_PILE_UPDATE = True
REAL_GAME = False

if REAL_GAME:
    NB_CARDS = 104
    NB_CARDS_IN_HAND = 10
    NB_OPPONENTS = 4
    NB_PILES = 4
else:
    NB_CARDS_IN_HAND = 4
    NB_OPPONENTS = 2
    NB_PILES = 3
    # NB_CARDS_MAX_FOR_PILE = 3

NB_CARDS = NB_PILES + (NB_OPPONENTS+1) * NB_CARDS_IN_HAND
